version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2022!"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network
    volumes:
      - ./mysqlScripts:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge