version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2022!"
      MYSQL_DATABASE: "spring_batch"
    ports:
      - "3306:3306"
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8888:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge